---
- name: This playbook is to create file
  hosts: all
  become: true
  tasks:
    - name: This task is to create file - Ansible file.
      file:
        path: /home/ansadmin/demofile
        state: touch
        # if we mention state as directory then it will create a directory demofile
        # state: absent -> to delete
