---
- name: My Test Playbook
  hosts: all
  become: true

  vars_files:
    - test.yml

  tasks:
    - name: creating user {{ user1 }}
      user:
        name: "{{ user1 }}"
        state: present

    - name: creating user {{ user2 }}
      user:
        name: "{{ user2 }}"
        state: present
